# Generated by Django 5.2 on 2025-04-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
