# Generated by Django 5.2 on 2025-04-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
